/*
 * Camera API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xrc.camera.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ShutterSpeedInfo
 */


public class ShutterSpeedInfo extends BaseSettingInfo<Long> {
  @JsonProperty("value")
  private Long value = null;

  @JsonProperty("values")
  private java.util.List<Long> values = new java.util.ArrayList<>();

  public ShutterSpeedInfo value(Long value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   *
   * @return value
   **/
  @Schema(required = true, description = "")
  public Long getValue() {
    return value;
  }

  public void setValue(Long value) {
    this.value = value;
  }

  public ShutterSpeedInfo values(java.util.List<Long> values) {
    this.values = values;
    return this;
  }

  public ShutterSpeedInfo addValuesItem(Long valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

  /**
   * Get values
   *
   * @return values
   **/
  @Schema(required = true, description = "")
  public java.util.List<Long> getValues() {
    return values;
  }

  public void setValues(java.util.List<Long> values) {
    this.values = values;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShutterSpeedInfo shutterSpeedInfo = (ShutterSpeedInfo) o;
    return Objects.equals(this.value, shutterSpeedInfo.value) &&
            Objects.equals(this.values, shutterSpeedInfo.values) &&
            super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, values, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShutterSpeedInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
