camera.host: 192.168.0.136
camera.port: 9001

client.debug: false
client.timeout: 10000

camera.settings.cache: true

test.iso.maxValueError: 300
test.iso.manual.maxValueError: 10


test.selfie-robot.iterations: 5
test.selfie-robot.delay: 1000
